version: '3'
services:
  redis:
    image: redis

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: diary

  server:
    image: hardik/diary:1.0.0
    ports:
      - '4000:4000'
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      NODE_ENV: production
    depends_on:
      - db
      - redis
