version: '3.3'
services:
  redis:
    expose:
      - '6379'
    restart: always
    ports:
      - '6379:6379'
    image: redis

  db:
    restart: always
    image: postgres:11.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: diary

  server:
    restart: always
    image: hardik/diary:1.0.0
    expose:
      - '4000'
    ports:
      - 4000:4000
    environment:
      REDIS_HOST: redis
      DB_HOST: db
      NODE_ENV: production
    depends_on:
      - db
      - redis
