version: '3'
networks:
  main:
volumes:
  db-postgres:
services:
  redis:
    restart: always
    image: redis
    networks:
      - main

  db:
    image: postgres
    restart: always
    volumes:
      - db-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'diary'
    networks:
      - main

  server:
    restart: always
    image: hardik/diary:1.0.0
    ports:
      - '3001:4000'
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    depends_on:
      - db
      - redis
    networks:
      - main
